### ISSUE TITLE
为什么下载的代码 运行和 预览小程序demo不一样

### ISSUE THREAD

**Issue by yb1994917** [Tencent/weui-wxss#109]

**Comment by Sun-Shuai** [comment]
同问

**Comment by BearJ** [comment]
@yb1994917 微信开发者工具打开的需要是 /dist 目录

**Comment by Sun-Shuai** [comment]
@BearJ 就是打开的/dist目录，但是编译运行和README给的小程序码预览的效果不一样的

**Comment by BearJ** [comment]
@Sun-Shuai 你运行的时候有报错吗？运行的效果是如何的？截图看看？

**Comment by Sun-Shuai** [comment]
@BearJ 

扫描Demo的小程序码运行截图：
![11565138401_ pic](https://user-images.githubusercontent.com/15135854/62586176-17f2e680-b8ef-11e9-8fb4-745019dad635.jpg)
![21565138402_ pic](https://user-images.githubusercontent.com/15135854/62586180-1d503100-b8ef-11e9-95f2-819b3006546f.jpg)
![31565138403_ pic](https://user-images.githubusercontent.com/15135854/62586183-204b2180-b8ef-11e9-8d88-170363883250.jpg)
![41565138404_ pic](https://user-images.githubusercontent.com/15135854/62586185-23dea880-b8ef-11e9-9c91-17b28ad5c823.jpg)

编译源码运行截图：
![51565138406_ pic](https://user-images.githubusercontent.com/15135854/62586209-3953d280-b8ef-11e9-8e39-216ede5b8f44.jpg)
![61565138408_ pic](https://user-images.githubusercontent.com/15135854/62586212-3ce75980-b8ef-11e9-8d6c-56965b0452ae.jpg)
![71565138410_ pic](https://user-images.githubusercontent.com/15135854/62586215-3f49b380-b8ef-11e9-931c-c9bd5dace64c.jpg)
![81565138411_ pic_hd](https://user-images.githubusercontent.com/15135854/62586217-4244a400-b8ef-11e9-9df1-ba955f72bc67.jpg)

**Comment by Sun-Shuai** [comment]
@BearJ 没有报错。

分别截了四张图，左边是扫描Demo的小程序码运行结果，右边是编译源码运行结果。

第1组：
<div>
 <img src="https://user-images.githubusercontent.com/15135854/62586302-918ad480-b8ef-11e9-974b-a290cd7317d5.jpg" width = "270" height = "570" alt=""  />
 <img src="https://user-images.githubusercontent.com/15135854/62586329-aa938580-b8ef-11e9-8e2a-320805d2dfe2.jpg" width = "270" height = "570" alt=""  />
</div>

第2组：
<div>
 <img src="https://user-images.githubusercontent.com/15135854/62586523-9d2acb00-b8f0-11e9-8e01-9d7db4ec33e2.jpeg" width = "270" height = "570" alt=""  />
 <img src="https://user-images.githubusercontent.com/15135854/62586529-a320ac00-b8f0-11e9-86d5-255dec3fd8a9.jpeg" width = "270" height = "570" alt=""  />
</div>

第3组：
<div>
 <img src="https://user-images.githubusercontent.com/15135854/62586538-a61b9c80-b8f0-11e9-958f-754526855809.jpeg" width = "270" height = "570" alt=""  />
 <img src="https://user-images.githubusercontent.com/15135854/62586542-a87df680-b8f0-11e9-8ede-cf029f760093.jpeg" width = "270" height = "570" alt=""  />
</div>

第4组：
<div>
 <img src="https://user-images.githubusercontent.com/15135854/62586545-ab78e700-b8f0-11e9-9526-210ae53ae477.jpeg" width = "270" height = "570" alt=""  />
 <img src="https://user-images.githubusercontent.com/15135854/62586550-ad42aa80-b8f0-11e9-8488-036fbdebb0be.jpeg" width = "270" height = "570" alt=""  />
</div>

**Comment by Sun-Shuai** [comment]
OK了，pull 了新代码，2.0是一样的了

**Comment by Flora223** [comment]
请教一下。我用了2种方式。方式1：删除了dist目录，然后，cnpm i、gulp，重新放dist目录到微信开发工具里面，点击编译按钮；方式2：直接dist目录放入微信开发工具，点击编译按钮。  这2方式都没有办法出现，最新的demo展示情况，都是老demo展示。请问，我错在哪里了？

**Comment by Flora223** [comment]
> OK了，pull 了新代码，2.0是一样的了
请问，你是怎么做的啊？我的怎么不行啊

**Comment by uxsi** [comment]
@Flora223 麻烦pull一下最新代码重试呢？
