### ISSUE TITLE
weui-btn 样式失效

### ISSUE THREAD

**Issue by SevenOutman** [Tencent/weui-wxss#118]
`dist/style/weui.wxss` 中没有引入 `widget/weui-button/weui-button_global.wxss` 的代码，导致没有 `.weui-btn` 的样式。

**Comment by uxsi** [comment]
@SevenOutman 谢谢反馈，button是小程序原生内置组件，在weui-wxss里面只是扩展了按钮之间的一些间距规则，`widget/weui-button/`下的有效文件只有`weui-button.wxss`，这个目录下的其它文件会在下个版本里面删除，`weui-btn`是之前原生组件没有更新的时候用来hack的
