### ISSUE TITLE
有没有文档啊？

### ISSUE THREAD

**Issue by sir-ran** [Tencent/weui-wxss#124]
有没有文档啊？
有没有文档啊？
有没有文档啊？

**Comment by BearJ** [comment]
@sir-ran 如果是需要demo的话，可以扫这个二维码：
![image](https://user-images.githubusercontent.com/2395166/67002717-16277980-f10f-11e9-9265-5a374d0787dd.png)

如果是需要复制代码的话，可以看这里：https://github.com/Tencent/weui-wxss/tree/master/src/example

**Comment by FunkySamuel37** [comment]
没有文档，绝了
