### ISSUE TITLE
slide-view左滑露出右侧的按钮之后，如何用代码控制让右边的按钮缩回去？

### ISSUE THREAD

**Issue by pwf2006** [Tencent/weui-wxss#125]
slide-view左滑露出右侧的按钮之后，如何用代码控制让右边的按钮缩回去？

**Comment by ExileZhu** [comment]
同问 slide-view怎么用？

**Comment by ExileZhu** [comment]
> slide-view左滑露出右侧的按钮之后，如何用代码控制让右边的按钮缩回去？

https://developers.weixin.qq.com/miniprogram/dev/extended/weui/form.html 这里有使用文档 从github开始看 对我这样的新手不太友好 这里有正确的接入方式
