### ISSUE TITLE
@improt "weui.wxss"无任何效果

### ISSUE THREAD

**Issue by hawm** [Tencent/weui-wxss#129]
```
/**app.wxss**/
@import "weui.wxss";
@import "demo.wxss";
```
页面代码是直接复制自example中的示例。
而我的自定义样式demo.wxss中的样式是有效果的

没有提示路径错误或其它任何错误，是我的姿势不对吗？

**Comment by clockon** [comment]
路径不对。
![WeChat Screenshot_20191105155854](https://user-images.githubusercontent.com/56854654/68188899-34351b00-ffe5-11e9-91b5-ca8ef2fc8380.png)

**Comment by hawm** [comment]
> 路径不对。
> ![WeChat Screenshot_20191105155854](https://user-images.githubusercontent.com/56854654/68188899-34351b00-ffe5-11e9-91b5-ca8ef2fc8380.png)

但是我的demo.wxss和weui.wxss在同一个目录下却是有效果的，而且路径错误应该有提示的吧？

**Comment by clockon** [comment]
你可以检查你的路径有无写错，或者把代码贴出来。
我测试了多种写法多个路径都无问题，不知道具体你是什么情况。

**Comment by pinetreeps** [comment]
我也出现一样的问题，路径没有错误，但就是没生效

<view class="page">
    <view class="page__hd">
        <view class="page__title">WeUI</view>
        <view class="page__desc">WeUI 是一套同微信原生视觉体验一致的基础样式库，由微信官方设计团队为微信内网页和微信小程序量身设计，令用户的使用感知更加统一。</view>
    </view>
</view>

**Comment by zjh4473** [comment]
同样无效，无论如何都无效。样式没有任何改变

**Comment by jstdoit** [comment]
+1

**Comment by zjh4473** [comment]
我已解决该问题，我的解决方法，首先在app.json里加入style: "v2" 其次在选项设置里把微信的库设置成最新的。编辑器默认是2.4几，但是截止到发稿最新的都2.10了。

**Comment by hawm** [comment]
最近新建的项目没问题，解决方案应该是上面哪位所说的

**Comment by devpayapp** [comment]
刚刚新建的项目测试有此问题，和app.wxss同一级目录，@import 'weui.wxss';没有效果

**Comment by kookeda** [comment]
时间到了2022年，还是有同样的问题呢
![image](https://user-images.githubusercontent.com/12380902/186646290-1ec793d5-08ef-412e-9aba-32bdc0fac595.png)
![image](https://user-images.githubusercontent.com/12380902/186646652-30a00302-1935-4b3f-8abf-e2b090fa4153.png)
![image](https://user-images.githubusercontent.com/12380902/186646770-854d6eca-49ba-4c12-85a1-0cd7070ecba6.png)

**Comment by kookeda** [comment]
路径用@import '/style/weui.wxss';    @import 'style/weui.wxss';     @import './style/weui.wxss';都一样，放入同级目录也试了

**Comment by kookeda** [comment]
报了一个这个警告，Some selectors are not allowed in component wxss, including tag name selectors, ID selectors, and attribute selectors.
