### ISSUE TITLE
tabbar无法转换内容

### ISSUE THREAD

**Issue by devondahon** [Tencent/weui-wxss#135]
我新建了一个项目，安装了weui-wxss, 然后按照[说明书](https://developers.weixin.qq.com/miniprogram/dev/extended/weui/tabbar.html)使用了tabbar。两个默认的tabbar可以按但是页面怎么换？ 是要建立不同的组件(component)还是页面(page)。建立了之后怎么实行转换呢？
```
  tabChange(e) {
    console.log('tab change', e)
  }
```

**Comment by BearJ** [comment]
你好，请到这个项目下去提issue哈 https://github.com/wechat-miniprogram/weui-miniprogram/issues
