### ISSUE TITLE
radio会出现点击项与选中不统一

### ISSUE THREAD

**Issue by iijx** [Tencent/weui-wxss#15]
图1. 
![2016-12-07 13 21 05](https://cloud.githubusercontent.com/assets/19170733/20955693/29960976-bc80-11e6-9965-5aea75be6548.png)

图2.
![11](https://cloud.githubusercontent.com/assets/19170733/20955539/f2b91804-bc7e-11e6-8b92-c328083639bf.png)

如图，当点击“500元”与“800元”交界线处的时候，容易出现点击效果（背景变暗）与选中项不同。

**Comment by BearJ** [comment]
你好，开发者工具的确有这个问题，手机上是没有的~

**Comment by iijx** [comment]
小程序里面，这种现象在手机上也是有的（weui网页上的确没有），截图如下
![wechatimg121](https://cloud.githubusercontent.com/assets/19170733/20959738/8356de7e-bc97-11e6-8259-a0227156ff3a.png)

这是官网的weui小程序的例子在手机上的测试截图（我是用我这边的appid在手机上体验的）

**Comment by BearJ** [comment]
@iijx 明白了，等我们检查一下

**Comment by iijx** [comment]
@BearJ  手机用的是红米3s, 系统安卓6.0.1,微信是安卓最新版（6.3.31）

**Comment by BearJ** [comment]
@iijx 好的，我们查一下~

**Comment by BearJ** [comment]
@iijx 更新到最新版微信试试？
