### ISSUE TITLE
IOS16.0 版本 显示异常？

### ISSUE THREAD

**Issue by synctimes163** [Tencent/weui-wxss#190]
IOS16.0 版本 显示异常？preview

![6d0aa6bc2d1c49a13101578a04d508a](https://user-images.githubusercontent.com/78259973/189814940-a4990b82-4b79-43bd-b5af-0beaa3b4fbb0.jpg)
![6c391f20d05c8e531a49d30968ef29b](https://user-images.githubusercontent.com/78259973/189814962-b10a403a-5c5d-4f65-ace7-b20a16b5bd1d.jpg)

**Comment by liantian-cn** [comment]
同样遇到问题...

**Comment by liantian-cn** [comment]
IOS 15.7 没这个问题..

**Comment by IACJ** [comment]
同遇到问题

**Comment by uxsi** [comment]
[新版本](https://github.com/Tencent/weui-wxss/releases/tag/v2.5.13)已经修复了
