### ISSUE TITLE
picker不能同时出现日期和时间

### ISSUE THREAD

**Issue by baiyuxiong** [Tencent/weui-wxss#24]
在example的input示例中：
`<picker mode="time" value="{{time}}" start="09:01" end="21:01" bindchange="bindTimeChange">
        <view class="weui-input">{{time}}</view>
</picker>`
https://weui.io/#input 这里显示的是同时有日期和时间的格式。
但是放在小程序时只有时间，没有日期

**Comment by BearJ** [comment]
@baiyuxiong 那你试试mode="date"

**Comment by BearJ** [comment]
目前小程序的picker不能同时出现日期和时间，所以只能用两个picker来控制，一个mode="time"，一个mode="date"
