### ISSUE TITLE
input中的文字对齐问题

### ISSUE THREAD

**Issue by UXplayer** [Tencent/weui-wxss#25]
系统默认的css中，input里的文字和普通text在y坐标有很大的偏差；
weui-wxss已经较好的解决了这个问题，在示例demo中非常完美，只是还有一个小瑕疵：
如果一个input表单没有放入weui-cell weui-cell_input这个view中
weui-input中的文字会比weui-label中的低约1rpx
![image](https://cloud.githubusercontent.com/assets/16333847/21976796/802a85a2-dc0e-11e6-8314-cce3d614a4d2.png)

ps：能否问个题外话，作者是微信官方团队的人员吗？

**Comment by BearJ** [comment]
@UXplayer 这里是用到flex的居中对齐，这个问题我去看看。

**Comment by BearJ** [comment]
问题解决，已经不需要weui-cell weui-cell_input 两个类名了
