### ISSUE TITLE
navbar内容滚动后覆盖导航栏

### ISSUE THREAD

**Issue by runtop** [Tencent/weui-wxss#27]
![jdgz7bfkyh1mii 72 1j6tb](https://cloud.githubusercontent.com/assets/7489318/22180257/33e39822-e0a6-11e6-884b-71a3ff73db4c.png)
![hn fzo6f g8ry xy50w4do](https://cloud.githubusercontent.com/assets/7489318/22180260/364c5928-e0a6-11e6-93fa-2961b285c32e.png)
![wr 4f 33b h2 7 4 f_tfih](https://cloud.githubusercontent.com/assets/7489318/22180261/378fda80-e0a6-11e6-8908-8c4ce1912256.png)

**Comment by BearJ** [comment]
@runtop 这里你是需要给navbar设一个背景色的，因为我们并不知道开发者项目的背景色，所以这里是没有设置~
