### ISSUE TITLE
TypeError: window.__generateFunc__ is not a function

### ISSUE THREAD

**Issue by bestony** [Tencent/weui-wxss#28]
同样的代码，在无AppID时可以正常使用。
在有Appid时就会报错。
![-171260532](https://cloud.githubusercontent.com/assets/13283837/22333953/9501302c-e413-11e6-90f1-dd9214c865c2.png)

**Comment by BearJ** [comment]
@bestony 这个问题你可以在 [微信开发者社区](https://developers.weixin.qq.com/) 进行反馈～

**Comment by bestony** [comment]
好的，我以为是因为WeUI的问题。

**Comment by hdwmp123** [comment]
我也遇到同样的问题，不知道为啥

**Comment by hdwmp123** [comment]
微信web开发者工具 v0.14.140900

**Comment by xuhen** [comment]
应该是.wxml的文件末尾有换行的空格

**Comment by ChenZerong** [comment]
同样遇到这个问题，尝试重启微信开发工具之后就可以了
