### ISSUE TITLE
demo中input控件右边框多了1像素

### ISSUE THREAD

**Issue by mablevi** [Tencent/weui-wxss#30]
input控件里 微信号和国家/地区 引用了+86的样式weui-select 右边框多了1像素

**Comment by BearJ** [comment]
@mablevi 实现是按高分屏1px线的方式实现的，你看看其它设备是否也有问题？

**Comment by ygwoo** [comment]
input 选择控件显示有问题，右侧会多显示一个边框

**Comment by BearJ** [comment]
谢谢，这的确是bug~

**Comment by BearJ** [comment]
已fixed
