### ISSUE TITLE
能否列一份样式图

### ISSUE THREAD

**Issue by LaelLuo** [Tencent/weui-wxss#35]
因为刚开始用不知道某些样式是作用于什么组件的

**Comment by BearJ** [comment]
@Yamiku 额。。样式图是什么？不过，作用关系不难理解吧？类名的中间的一部分就是这个组件的名字。然后你在对应组件调试一下不就可以知道了？

**Comment by Yamiku** [comment]
比如.weui-cells是什么作用于什么组件的。。。。。

**Comment by BearJ** [comment]
@Yamiku 这个可以有，但个人觉得调试比较靠谱...毕竟文档更新会有延时...

**Comment by Yamiku** [comment]
是的，但是这样方便刚接触新手快速上手
