### ISSUE TITLE
tabbar表单太大上下滚动会遮挡标题

### ISSUE THREAD

**Issue by kiddkyd1412** [Tencent/weui-wxss#41]
表单就是weui里面那种一行一行view的格式
当这个表单超出屏幕高度后，并且page样式设置到height:100%的时候
当上下滚动这个表单的时候，tabbar的标题部分会被表单遮挡，即使把标题的z-index设置很大也无效。

**Comment by kiddkyd1412** [comment]
我知道了。需要给设置一个背景色，才可以遮挡
.weui-navbar{
    background-color:#F8F8F8;
}

**Comment by BearJ** [comment]
@kiddkyd1412 嗯嗯，是的~
