### ISSUE TITLE
border为什么没有用0.5px

### ISSUE THREAD

**Issue by overwhats** [Tencent/weui-wxss#42]
border是用伪元素实现的，可最后没有用transform压缩。为什么要这么设计呢，如果不需要0.5px直接用border不是更方便

**Comment by BearJ** [comment]
@overwhats weui-wxss用的是rpx，这个单位是可以实现高清线的。0.5px有兼容性问题

**Comment by mangoooooo** [comment]
@BearJ  1rpx的边框 看上去要比 原生按钮的边框和tabbar的上边框要粗？请问有什么解决方法吗？

**Comment by BearJ** [comment]
@mangoooooo 目前没有更好的解决方案，只能先用1rpx来实现。
