### ISSUE TITLE
导入后 报错 样式也都不对（微信web开发者工具 v0.17.171900)

### ISSUE THREAD

**Issue by zeroHu** [Tencent/weui-wxss#43]
![image](https://cloud.githubusercontent.com/assets/14057313/26489144/c653bb62-4238-11e7-829f-acc12830aaef.png)

**Comment by zeroHu** [comment]
导入的是 src 项目 dist 未发现问题 （求问 dist 不应该是src的压缩目录吗 src报错 dist不报错 ？？？）

**Comment by suyunlongsy** [comment]
你看看源码 一个编译过 ，一个没编译

**Comment by BearJ** [comment]
@zeroHu src是这个项目的源码，dist才是生成出来可用的产品哈~
