### ISSUE TITLE
base64 is not defined

### ISSUE THREAD

**Issue by perezpz** [Tencent/weui-wxss#49]
<img width="472" alt="2017-07-28 7 03 24" src="https://user-images.githubusercontent.com/10556818/28714812-bf84ec78-73c7-11e7-88dc-875c203e723f.png">
打开的是dist目录，
调试版本信息： v0.20.191900

**Comment by Yanjunhui** [comment]
同样的问题 +1  最新版的小程序  之前的老版本正常

**Comment by BearJ** [comment]
这个问题可以在 [微信开发者社区](https://developers.weixin.qq.com/) 问问？
