### ISSUE TITLE
为什么度量单位不用rpx，而都用的px呢？

### ISSUE THREAD

**Issue by wangxiaochuang** [Tencent/weui-wxss#52]

**Comment by BearJ** [comment]
@wangxiaochuang 因为rpx更适合于随屏幕拉伸而拉伸的页面设计。weui-wxss这种功能型的组件用px就好~

**Comment by sherlock221** [comment]
https://github.com/sherlock221/weui-wxss-rpx 可以使用修改过的 rpx版本看看
