### ISSUE TITLE
打开日期选择器100%崩溃【小米6，微信6.5.16】

### ISSUE THREAD

**Issue by callmepeanut** [Tencent/weui-wxss#53]
如题，在weui的小程序里100%复现。

**Comment by green-dalii** [comment]
我也发现此问题，模拟器中正常，真机（Nexus6P，Android 8.0，微信6.5.10）只要选择日期Picker就崩溃闪退，望解决。

**Comment by green-dalii** [comment]
`date" value="{{date}}" start="2015-09-01" end="2017-09-01" bindchange="bindDateChange"`

已发现Bug，在Picker的属性中，若定义日期区间start="2015-09-01" end="2017-09-01，则必崩溃，删除日期区间则正常。

**Comment by BearJ** [comment]
@green-dalii 用新版的微信试试？
