### ISSUE TITLE
preview组件中 label在iOS和Android平台显示的不一样

### ISSUE THREAD

**Issue by cnazev** [Tencent/weui-wxss#55]
.weui-form-preview__label

在Android平台中(微信开发工具模拟器与真机) label有最小四个中文字符的宽度,如果少于四个中文字符,会被拉长(红米note2).
iOS真机上显示不会被拉长[ip6s,ios10.3.3] (微信开发工具模拟器上会被拉长)

**Comment by BearJ** [comment]
@cnazev 方便提供一下截图吗？
