### ISSUE TITLE
input 焦点问题

### ISSUE THREAD

**Issue by meidea** [Tencent/weui-wxss#56]
dist里的input示例里，点击qq输入框，取得焦点，然后点击手机号输入框，过一会才能取得焦点，这个延迟怎么能避免？因为这样会导致键盘反复的显示、隐藏

另外，当获取焦点时，placeholder会略微上移，在不同的input之间切换焦点时，焦点总是从输入框的最后移动到第一位，这样就导致placeholder会有闪烁

**Comment by BearJ** [comment]
目前无解，可以到https://developers.weixin.qq.com/提出这个问题
