### ISSUE TITLE
用了WEPY框架还能用这个组件库吗

### ISSUE THREAD

**Issue by Liqiankun** [Tencent/weui-wxss#62]

**Comment by a24576946** [comment]
能是能，但是没文档，就不知道怎么引用，擦，组件怎么引用， 都不讲，给个库有毛用

**Comment by kennylbj** [comment]
期待官方能出个```weui-wxss```用在```wepy```上的文档

**Comment by Liqiankun** [comment]
只能看这个了[wepy-weui-demo](https://github.com/wepyjs/wepy-weui-demo)
