### ISSUE TITLE
可不可以增加个上拉加载下拉刷新的功能呀

### ISSUE THREAD

**Issue by 290352095** [Tencent/weui-wxss#63]
其实，把其他ui框架中都继承进来就好了

**Comment by uxsi** [comment]
@290352095 weui-wxss本意是方便开发者开发的页面视觉体验效果与微信原生体验统一而提供的小程序UI库，加载中的样式应该是可以满足基本需求的了：[loadmore](https://github.com/Tencent/weui-wxss/blob/master/src/style/widget/weui-tips/weui-loadmore.wxss)、[loading](https://github.com/Tencent/weui-wxss/tree/master/src/style/widget/weui-loading)
