### ISSUE TITLE
是否继续维护更新？

### ISSUE THREAD

**Issue by alexfanwang** [Tencent/weui-wxss#66]
离上一个release版本已经一年了，请问这个项目是否还继续维护更新吗？

**Comment by ystarlongzi** [comment]
同问 @progrape @codeif

**Comment by vangogogo** [comment]
同问

**Comment by lixiaolihua** [comment]
同问

**Comment by youngjuning** [comment]
同问@progrape

**Comment by NullYing** [comment]
同问

**Comment by HelloWorld1991** [comment]
同问

**Comment by rebider** [comment]
自己fix吧，靠自己最可靠

**Comment by jianghuzai** [comment]
额，直接用还可以，但是要想改，发现很难，panle里面，都不知道什么时候会有边框，什么时候没有，修改position属性也会影响到边框，，我凌乱中……

**Comment by jbasttdi** [comment]
如果腾讯这货说还会在1年后继续维护，你们信吗

**Comment by ThatToti** [comment]
看那几个 commiter 连 github 都不活跃了...很难相信这个项目还有人维护

**Comment by super-ppx** [comment]
死掉了，用有赞吧

**Comment by uxsi** [comment]
会持续更新的，谢谢关注，weui是对齐微信原生视觉体验提供的样式库，同步需要时间，请见谅
