### ISSUE TITLE
很多长宽，边距单位怎么不是rpx？

### ISSUE THREAD

**Issue by lizongwen** [Tencent/weui-wxss#71]
很多长宽，边距单位怎么不是rpx？

**Comment by sherlock221** [comment]
https://github.com/sherlock221/weui-wxss-rpx 可以使用修改过的 rpx版本看看

**Comment by github-zhang** [comment]
同问！ 为什么不用官方推荐的rxp？

**Comment by uxsi** [comment]
谢谢关注这个细节，rpx的作用更多的是实现一个模块在不同设备上的等比缩放效果，如果布局本来就是响应式或者需求就是固定值的话就不需要了
