### ISSUE TITLE
loading icon 是不是反了？

### ISSUE THREAD

**Issue by sunderls** [Tencent/weui-wxss#72]
https://github.com/Tencent/weui-wxss/blob/master/src/example/loadmore/loadmore.wxml#L8

https://github.com/Tencent/weui-wxss/blob/fbd7c04e2d5fa24b3ad8f62f4477045477207cfb/dist/style/widget/weui-loading/weui-loading.wxss#L6

这个loading icon，顺时针旋转的话是反的啊？看上去有点别扭

**Comment by uxsi** [comment]
谢谢反馈，设计如此，v2.0丰富了loading的样式，需要的话可以[看看](https://github.com/Tencent/weui-wxss/tree/master/src/style/widget/weui-loading)
