### ISSUE TITLE
navbar的动效在ios真机会出bug

### ISSUE THREAD

**Issue by nickzhuo** [Tencent/weui-wxss#76]
`<view class="weui-navbar__slider" style="left: {{sliderLeft}}px; transform: translateX({{sliderOffset}}px); -webkit-transform: translateX({{sliderOffset}}px);"/>`

在IOS真机渲染下有问题，切换tab的时候silder有延迟，官方demo亦是如此。

**Comment by BearJ** [comment]
这个是css动画有卡顿，可以去微信开放社区问问哈： https://developers.weixin.qq.com/
