### ISSUE TITLE
weui-cell__ft_in-access 为何会没有icon

### ISSUE THREAD

**Issue by kiros1986** [Tencent/weui-wxss#77]
如题 我直接引入weui.wess后 weui-cell__ft_in-access 没有三角形

**Comment by GrougChar** [comment]
图片吧！

**Comment by kid1211** [comment]
那个三角形应该是css 里面一个 :after 加进去的，但是那个css file感觉没有被应用，如果有人知道可以留下言吗？ 谢谢

**Comment by lw254605953** [comment]
> 把这个里面的文字删除就可以只有三角形了

那个里面？？？

**Comment by uxsi** [comment]
请更新最新版试试呢？
