### ISSUE TITLE
如何删除上传的图片？

### ISSUE THREAD

**Issue by Cdyizhaoqusheng** [Tencent/weui-wxss#83]
大佬，能不能留个联系方式什么的  有不明白的请教一下，最近开发小程序，困惑比较多，还请留下联系方式，麻烦，麻烦，麻烦。

**Comment by linzcity** [comment]
<view class='img'>
        <view class="weui-cells">
          <view class="weui-cell">
            <view class="weui-cell__bd">
              <view class="weui-uploader">
                <view class="weui-uploader__hd">
                  <view class="weui-uploader__title" style='font-size:29rpx'>上传图片</view>
                  <view class="weui-uploader__info">{{imageList.length}}/9</view>
                </view>
                <view class="weui-uploader__bd">
                  <view class="weui-uploader__files">
                    <block wx:for="{{imageList}}" wx:for-item="image">
                      <view class="weui-uploader__file">
                        <text class='iconfont icon-cha2 my_icon' data-i_index='{{index}}' bindtap='delect_img'></text>
                        <image class="weui-uploader__img" src="{{image}}" data-src="{{image}}" bindtap="previewImage" mode='aspectFill'></image>
                      </view>
                    </block>
                  </view>
                  <view class="weui-uploader__input-box">
                    <view class="weui-uploader__input" bindtap="chooseImage"></view>
                  </view>
                </view>
              </view>
            </view>
          </view>
        </view>
      </view>

// 预览图片
  previewImage: function (e) {
    var current = e.target.dataset.src
    wx.previewImage({
      current: current,
      urls: this.data.imageList
    })
  },

  // 选择图片
  chooseImage: function () {
    var length = this.data.imageList.length
    if (length >= 9) {
      wx.showToast({
        title: '最多选择9张图片',
      })
      return;
    }
    var that = this
    wx.chooseImage({
      sourceType: ['camera', 'album'],
      sizeType: ['compressed', 'original'],
      count: 9 - length,
      success: res => {
        var arr = this.data.imageList.concat(res.tempFilePaths);
        that.setData({
          imageList: arr
        })
      }
    })
  },

  delect_img: function (e) {
    console.log(e.target.dataset.i_index)
    var arr = this.data.imageList
    arr.splice(e.target.dataset.i_index, 1)
    this.setData({
      imageList: arr
    })
  },

  call: function (e) {
    wx.makePhoneCall({
      phoneNumber: '0769-86661001',
    })
  },

**Comment by linzcity** [comment]
![image](https://user-images.githubusercontent.com/40171365/47959574-f5136900-e022-11e8-97b7-c20c35f10f72.png)

![webwxgetmsgimg 2](https://user-images.githubusercontent.com/40171365/47959607-3e63b880-e023-11e8-9526-7af1588097c2.jpg)


供参考。可以实现预览、点击删除

**Comment by cangyu1993** [comment]
我看官网的demo里点击预览图片后下面有个删除按钮啊，为什么真机代码就没有了呢？

**Comment by uxsi** [comment]
图片预览组件[gallery](https://github.com/Tencent/weui-wxss/blob/master/src/style/widget/weui-cell/weui-gallery.wxss)最新代码已支持删除图片，谢谢反馈
