### ISSUE TITLE
图片不能添加替代文本？

### ISSUE THREAD

**Issue by hbwhzk** [Tencent/weui-wxss#84]
如果图片包含了大量信息，需要使用替代文本，而平台上似乎不能添加替代文本，这意味着视障人群使用的读屏软件或者辅助工具对于获取不了有效的图片信息。

**Comment by uxsi** [comment]
易用性这块一直都是我们关注的重要点，但是目前UI库在很多实现的细节上还在修修补补，后续稳定了会针对易用性这块进行更细致完善，谢谢关注
