### ISSUE TITLE
关于使用了navbar无法获取scroll-view事件的问题

### ISSUE THREAD

**Issue by acshmily** [Tencent/weui-wxss#86]
最近在学习小程序的开发,参考了navbar的样例进行了开发.
如果我需要在使用微信小程序的scroll-view组件获取bindscrolltolower事件进行动态追加内容的时候无法触发.请问有没有一个比较好的解决方案?
谢谢

**Comment by wxxyanmei** [comment]
navbar有做成左右滑动切换的吗？

**Comment by BearJ** [comment]
这个问题建议去微信开放社区问问哈： https://developers.weixin.qq.com/
