### ISSUE TITLE
微信浏览器ip漂移问题

### ISSUE THREAD

**Issue by wpstan** [Tencent/weui-wxss#87]
腾讯的朋友们，咨询两个问题。
1、用微信浏览器打开页面，会进行重定向，会首先访问weixin110.qq.com，这个可以关闭吗？
2、微信浏览器是不是会对请求做代理，每次接收到的客户端ip不一样，后台会对ip是否一致做校验，这就导致我们的功能在微信浏览器无法使用。

**Comment by BearJ** [comment]
这个问题建议去微信开放社区问问哈： https://developers.weixin.qq.com/
