### ISSUE TITLE
Dialog 组件按钮颜色 iOS 与 Android 不一致

### ISSUE THREAD

**Issue by zhanjiaxia** [Tencent/weui-wxss#89]
![image](https://user-images.githubusercontent.com/11500120/40757776-bbf8a7fc-64bc-11e8-967c-d8abf1ff9fb9.png)
![image](https://user-images.githubusercontent.com/11500120/40757778-bfb2e754-64bc-11e8-8816-4500b9561f85.png)

辅助操作按钮的颜色不一致, 是有什么原因吗 ?

**Comment by thumb0422** [comment]
这组件还有人维护吗

**Comment by uxsi** [comment]
[dialog](https://github.com/Tencent/weui-wxss/blob/master/src/style/widget/weui-tips/weui-dialog.wxss)已统一皮肤，谢谢反馈
