### ISSUE TITLE
全局引入了wxss后，原有的样式，不是以weui开头的view也受到了影响，会有所漂移

### ISSUE THREAD

**Issue by climbingDog** [Tencent/weui-wxss#90]
我的样式定义：
.topBar{
    position: relative;
    background-color: #1E90FF;
    width: 100%;
    color: white;
    font-family: '微软雅黑';
    font-weight: 200;
}
.topBar .whichDate{
    display: inline-block;
    padding: 0px 0rpx 10rpx 20rpx;
    font-size: 70rpx;
}
.topBar .whichYear{
    display: inline-block;
    vertical-align: top;
    padding-top: 15rpx;
    font-size: 28rpx;
}
.topBar .nongliDetail{
    position: absolute;
    right: 10rpx;
    bottom: 10rpx;
}
.monthBox{
    width: 96%;
    padding: 0 2%;
}
.weekDay{
    display: flex;
    flex-grow: 1;
}
.weekDay .week{
    display: flex;
    width: 200rpx;
    margin-top: 30rpx;
    margin-bottom: 10rpx;
    justify-content: center;
    font-family:'微软雅黑';
    font-weight: 200;
}
.monthDay{
    width: 100%;
}
.monthDay .tr{
    width: 100%;
    display: flex;
    flex-grow: 1;
}
.monthDay .tr .day{
    display: block;
    width: 200rpx;
    height: 80rpx;
    padding-top: 10rpx;
    border-radius: 5px;
    margin-top: 5px;
    margin-bottom: 5rpx;
    text-align: center;
    color: #999;
    border: 1rpx solid white;
}
.monthDay .tr .day.hideDayInfo{
    border: 1rpx solid white;
}
.monthDay .tr .day.showDayInfo{
    border:1rpx solid #1E90FF;
}
.monthDay .tr .today{
    background-color: #1E90FF;
    color:white;
}
.monthDay .tr .day .gongli{
    display: block;
    font-family:Arial, Helvetica, sans-serif;
}
.monthDay .tr .day .nongli{
    display: block;
    font-family: "微软雅黑";
    font-weight: 200;
    font-size: 20rpx;
    text-align: center;
}

我的view：
------------------------------------分割线-------------------------------------------

<view class="topBar">
    <view class="whichDate">{{toMonth}}月{{toDate}}日</view>
    <view class="whichYear">
        <text>{{toYear}}年\n</text>
        <text>{{fromToday}}</text>
    </view>
    <view class="nongliDetail">
        {{nongliDetail}}
    </view>
</view>
<view class="monthBox" >
    <view class="weekDay">
        <view class="week">日</view>
        <view class="week">一</view>
        <view class="week">二</view>
        <view class="week">三</view>
        <view class="week">四</view>
        <view class="week">五</view>
        <view class="week">六</view>
    </view>
    <view class="monthDay">
        <view class="tr" wx:for="{{MonthDayArray}}" wx:key="month">
            <view id="{{item.num}}" class="day {{item.isShowDayInfo ? 'showDayInfo':'hideDayInfo'}} {{item.isToday ? 'today' : ''}}" wx:for="{{item}}" bindtap="dateClick" wx:key="day">
                <text class="gongli">{{item.num}}</text>
                <text class="nongli">{{item.nongli}}</text>
                
            </view>
        </view>
    </view>
    
    
</view>

**Comment by bless-19946** [comment]
请问你是通过什么方式引入的wxss
复制 还是npm包的方式
