### ISSUE TITLE
表单->input->文本域 ，右下角的字符数没有随内容改变呢

### ISSUE THREAD

**Issue by er567** [Tencent/weui-wxss#94]
这个操作是扫demo二维码复现的，显示更新时间是2017年8月17日。

**Comment by uxsi** [comment]
demo只是做了一个文本域的样式展示，没有完整的逻辑功能，谢谢关注。另外官方提供了一套封装版的[小程序扩展组件库](https://developers.weixin.qq.com/miniprogram/dev/extended/weui/)，需要的话可参阅
