### ISSUE TITLE
BUG : 使用 navbar 组件的时候报错

### ISSUE THREAD

**Issue by ThatToti** [Tencent/weui-wxss#95]
![image](https://user-images.githubusercontent.com/17880183/47427176-29388f80-d7c2-11e8-94dd-814f9aba3d72.png)

在demo 中,有一个变量`sliderWidth`没有声明,导致报错
![image](https://user-images.githubusercontent.com/17880183/47427207-3d7c8c80-d7c2-11e8-83aa-94c75d46722a.png)

**Comment by BearJ** [comment]
@ThatToti 在顶部有作声明：https://github.com/Tencent/weui-wxss/blob/master/dist/example/navbar/navbar.js
