### ISSUE TITLE
求助图片展示组件：变形怎么处理？

### ISSUE THREAD

**Issue by linzcity** [Tencent/weui-wxss#98]
![webwxgetmsgimg 2](https://user-images.githubusercontent.com/40171365/47959667-ce563200-e024-11e8-8540-01ce91dc4205.jpg)

设置mode还是会变形。有什么办法可以类似
```css
/*缺点就是只能通过设置background-image:url('')实现，但是小程序这种方式只支持链接........*/
background-position: center;
background-size: cover;
```
实现截取展示中间部分——至少保证不变形。

**Comment by zhuyuping** [comment]
删除按钮是weui自带的吗

**Comment by linzcity** [comment]
> ![webwxgetmsgimg 2](https://user-images.githubusercontent.com/40171365/47959667-ce563200-e024-11e8-8540-01ce91dc4205.jpg)
> 
> 设置mode还是会变形。有什么办法可以类似
> 
> ```css
> /*缺点就是只能通过设置background-image:url('')实现，但是小程序这种方式只支持链接........*/
> background-position: center;
> background-size: cover;
> ```
> 
> 实现截取展示中间部分——至少保证不变形。

纠正：发现使用mode不会变形。

**Comment by linzcity** [comment]
> 删除按钮是weui自带的吗

不是的，是我自己写的。

**Comment by BearJ** [comment]
@linzcity 用`mode="aspectFill"`
