### ISSUE TITLE
导入weui后报错

### ISSUE THREAD

**Issue by M1SAK1TN** [Tencent/weui-wxss#99]
![image](https://user-images.githubusercontent.com/45626376/49921482-93c79b00-fee8-11e8-9a42-4218ff02c6de.png)
我看教程都没有报错，我使用就会报错，请问是什么原因呢

**Comment by BearJ** [comment]
@M1SAK1TN 打开/dist目录，dist目录下是没有weui.wxss文件的，你删掉试试？
